version: '3'

volumes:
  pg_data_kittygram:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
backend:
    build: ./backend/
    image: greatadmin/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - kittygram
frontend:
    build: ./frontend/
    image: greatadmin/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kittygram:/frontend_static
      - media:/media
gateway:
    build: ./nginx/
    image: greatadmin/kittygram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 9000:80
